name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: newsletter
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 2s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: sqlx-cli

      - name: Install latest toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          #components: rustfmt, clippy

      - name: Init schema
        run: sqlx migrate run

      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo

      - name: Cargo Target Cache
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target

      - name: Build
        run: cargo build
      #- name: Run tests
      #  run: cargo test

      - name: Deploy to aliyun
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_USER: 'root' #ssh user name
          REMOTE_HOST: ${{secrets.HOST_ALIYUN}}
          ARGS: '-avz --delete' #参数
          SSH_PRIVATE_KEY: ${{secrets.ACCESS_TOKEN_ALIYUN}} #github access token
          # work dir: /home/runner/work/zero2prod/zero2prod
          SOURCE: 'target/debug/zero2prod configuration ../../../.cargo/bin/sqlx'
          # Be careful: All other files under target dir will be deleted without prompt
          TARGET: '/root/dist/'
          # 上面几个参数可以在github secrets中设置,然后用secrets.的模式引用
          SCRIPT_BEFORE: |
            ps -ef|grep zero2prod
            pkill -f zero2prod
            whoami
            ls -al
          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT
            whoami
            ls -al
            set -vx
            cd /root/dist
            # redirect the output to log file and put job into background, 
            # so the Action can continue the subsequent steps.
            nohup ./zero2prod >zero2prod.log 2>&1 &